require: rubocop-rspec

########## Layout #############

Layout/AlignHash:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/IndentArray:
  EnforcedStyle: consistent

########### Lint ##############

Lint/AmbiguousBlockAssociation:
  Enabled: false

########## Metrics ############

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 15

Metrics/ParameterLists:
  Enabled: false

########### Naming ############

Naming/PredicateName:
  NamePrefixBlacklist:
    - "is_"
    - "have_"

Naming/UncommunicativeMethodParamName:
  AllowedNames:
    - id
    - io
    - ko

######### Performance #########
Performance/RegexpMatch:
  Enabled: false

############ RSpec ############
RSpec/MultipleExpectations:
  Max: 2

RSpec/NestedGroups:
  Max: 4

########## Security ###########

Security/Eval:
  Enabled: false

########### Style #############

Style/BlockDelimiters:
  AutoCorrect: false
  Exclude:
    - "spec/**/*"

Style/ClassCheck:
  EnforcedStyle: kind_of?

Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition
  IncludeTernaryExpressions: false

Style/DoubleNegation:
  Enabled: false

Style/FormatString:
  EnforcedStyle: percent

Style/FrozenStringLiteralComment:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/PreferredHashMethods:
  Enabled: false

Style/RegexpLiteral:
  AllowInnerSlashes: true

Style/Semicolon:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  MinSize: 3

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingUnderscoreVariable:
  Enabled: false

# These cops should be turned on, but temporarily disabled
# To be fixed
Metrics/LineLength:
  Max: 106

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false
